-- Regex flags are generated by the challenge service rather than an Anvil
-- instance, so a repeated regex value has no owner instance to reference.
ALTER TABLE flag_share_events
    ALTER COLUMN owner_instance_id DROP NOT NULL;

COMMENT ON COLUMN flag_share_events.owner_instance_id IS
    'Originating instance for generated flags; NULL for regex flag matches';
